NTDHBaiKiemTraGK/NTDHBaiKiemTraGK/Models/NTDHKhoa.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NTDHBaiKiemTraGK.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NTDHKhoa
    {
        public string NTDHMaKH { get; set; }
        public string NTDHtenKH { get; set; }
        public Nullable<bool> NTDHTrangThai { get; set; }
    }
}

NTDHBaiKiemTraGK/NTDHBaiKiemTraGK/Models/NTDHModel2210900027.Context.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NTDHBaiKiemTraGK.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class NTDHCNTT2Lesson07DbEntities : DbContext
    {
        public NTDHCNTT2Lesson07DbEntities()
            : base("name=NTDHCNTT2Lesson07DbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<NTDHKhoa> NTDHKhoa { get; set; }
        public virtual DbSet<NTDHSinhVien> NTDHSinhVien { get; set; }
    }
}

NTDHBaiKiemTraGK/NTDHBaiKiemTraGK/Models/NTDHModel2210900027.Designer.cs
// T4 code generation is enabled for model 'D:\baitapASPNET\NTDH_cntt2_ASP.NET\NTDHBaiKiemTraGK\NTDHBaiKiemTraGK\Models\NTDH
//Model2210900027.edmx'. 
// To enable legacy code generation, change the value of the 'Code Generation Strategy' designer
// property to 'Legacy ObjectContext'. This property is available in the Properties Window when the model
// is open in the designer.

// If no context and entity classes have been generated, it may be because you created an empty model but
// have not yet chosen which version of Entity Framework to use. To generate a context class and entity
// classes for your model, open the model in the designer, right-click on the designer surface, and
// select 'Update Model from Database...', 'Generate Database from Model...', or 'Add Code Generation
// Item...'.

NTDHBaiKiemTraGK/NTDHBaiKiemTraGK/Models/NTDHModel2210900027.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

NTDHBaiKiemTraGK/NTDHBaiKiemTraGK/Models/NTDHSinhVien.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace NTDHBaiKiemTraGK.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class NTDHSinhVien
    {
        public string NTDHMaSV { get; set; }
        public string NTDHHoSV { get; set; }
        public string NTDHTenSV { get; set; }
        public Nullable<System.DateTime> NTDHNgaySinh { get; set; }
        public Nullable<bool> NTDHPhai { get; set; }
        public string NTDHPhone { get; set; }
        public string NTDHEmail { get; set; }
        public string NTDHMaKH { get; set; }
    }
}

NTDHBaiKiemTraGK/NTDHBaiKiemTraGK/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace NTDHBaiKiemTraGK.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

NTDHBaiKiemTraGK/NTDHBaiKiemTraGK/Controllers/NTDHKhoaController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using NTDHBaiKiemTraGK.Models;

namespace NTDHBaiKiemTraGK.Controllers
{
    public class NTDHKhoaController : Controller
    {
        private NTDHCNTT2Lesson07DbEntities db = new NTDHCNTT2Lesson07DbEntities();

        // GET: NTDHKhoa
        public ActionResult Index()
        {
            return View(db.NTDHKhoa.ToList());
        }

        // GET: NTDHKhoa/Details/5
        public ActionResult Details(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            NTDHKhoa NTDHKhoa = db.NTDHKhoa.Find(id);
            if (NTDHKhoa == null)
            {
                return HttpNotFound();
            }
            return View(NTDHKhoa);
        }

        // GET: NTDHKhoa/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: NTDHKhoa/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "NTDHMaKH,NTDHtenKH,NTDHTrangThai")] NTDHKhoa NTDHKhoa)
        {
            if (ModelState.IsValid)
            {
                db.NTDHKhoa.Add(NTDHKhoa);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(NTDHKhoa);
        }

        // GET: NTDHKhoa/Edit/5
        public ActionResult Edit(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            NTDHKhoa NTDHKhoa = db.NTDHKhoa.Find(id);
            if (NTDHKhoa == null)
            {
                return HttpNotFound();
            }
            return View(NTDHKhoa);
        }

        // POST: NTDHKhoa/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "NTDHMaKH,NTDHtenKH,NTDHTrangThai")] NTDHKhoa NTDHKhoa)
        {
            if (ModelState.IsValid)
            {
                db.Entry(NTDHKhoa).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(NTDHKhoa);
        }

        // GET: NTDHKhoa/Delete/5
        public ActionResult Delete(string id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            NTDHKhoa NTDHKhoa = db.NTDHKhoa.Find(id);
            if (NTDHKhoa == null)
            {
                return HttpNotFound();
            }
            return View(NTDHKhoa);
        }

        // POST: NTDHKhoa/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(string id)
        {
            NTDHKhoa NTDHKhoa = db.NTDHKhoa.Find(id);
            db.NTDHKhoa.Remove(NTDHKhoa);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

NTDHBaiKiemTraGK/NTDHBaiKiemTraGK/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

NTDHBaiKiemTraGK/NTDHBaiKiemTraGK/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "NGUYỄN THỊ DIỄM HƯƠNG";
}
<h2>@ViewBag.Title.</h2>
<h3>Bài Thi Giữa Kỳ của NGUYỄN THỊ DIỄM HƯƠNG-cam kết không đạo văn</h3>

<address>
    CNTT2 - Môn lập trình ứng dụng web với công nghệ Asp.net MVC5
</address>

<address>
    <strong>Support:</strong>   <a href="HUONGNTD1810@gmail.com">HUONGNTD1810@gmail.com</a><br />
    <strong>Cá nhân:</strong> <a href="HUONGNTD1810@gmail.com">HUONGNTD1810@gmail.com</a>
</address>

NTDHBaiKiemTraGK/NTDHBaiKiemTraGK/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

NTDHBaiKiemTraGK/NTDHBaiKiemTraGK/Views/NTDHKhoa/NTDHCreate.cshtml
@model NTDHBaiKiemTraGK.Models.NTDHKhoa

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>NTDHKhoa</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.NTDHMaKH, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NTDHMaKH, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NTDHMaKH, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NTDHtenKH, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NTDHtenKH, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NTDHtenKH, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NTDHTrangThai, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.NTDHTrangThai)
                    @Html.ValidationMessageFor(model => model.NTDHTrangThai, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

NTDHBaiKiemTraGK/NTDHBaiKiemTraGK/Views/NTDHKhoa/NTDHDelete.cshtml
@model NTDHBaiKiemTraGK.Models.NTDHKhoa

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>NTDHKhoa</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.NTDHtenKH)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NTDHtenKH)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NTDHTrangThai)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NTDHTrangThai)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

NTDHBaiKiemTraGK/NTDHBaiKiemTraGK/Views/NTDHKhoa/NTDHDetails.cshtml
@model NTDHBaiKiemTraGK.Models.NTDHKhoa

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>NTDHKhoa</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.NTDHtenKH)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NTDHtenKH)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.NTDHTrangThai)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.NTDHTrangThai)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.NTDHMaKH }) |
    @Html.ActionLink("Back to List", "Index")
</p>

NTDHBaiKiemTraGK/NTDHBaiKiemTraGK/Views/NTDHKhoa/NTDHEdit.cshtml
@model NTDHBaiKiemTraGK.Models.NTDHKhoa

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>NTDHKhoa</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.LtqMaKH)

        <div class="form-group">
            @Html.LabelFor(model => model.NTDHtenKH, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.NTDHtenKH, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.NTDHtenKH, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.NTDHTrangThai, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.NTDHTrangThai)
                    @Html.ValidationMessageFor(model => model.NTDHTrangThai, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

NTDHBaiKiemTraGK/NTDHBaiKiemTraGK/Views/NTDHKhoa/NTDHIndex.cshtml
@model IEnumerable<NTDHBaiKiemTraGK.Models.NTDHKhoa>

@{
    ViewBag.Title = "NTDHIndex";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("NTDH: Create New", "NTDHCreate")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.NTDHtenKH)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.NTDHTrangThai)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.NTDHtenKH)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.NTDHTrangThai)
        </td>
        <td>
            @Html.ActionLink("NTDH:Edit", "NTDHEdit", new { id=item.NTDHMaKH }) |
            @Html.ActionLink("NTDH:Details", "NTDHDetails", new { id=item.NTDHMaKH }) |
            @Html.ActionLink("NTDH:Delete", "NTDHDelete", new { id=item.NTDHMaKH })
        </td>
    </tr>
}

</table>

NTDHBaiKiemTraGK/NTDHBaiKiemTraGK/Views/Shared/_NTDHLayout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("NGUYỄN THỊ DIỄM HƯƠNG", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("About", "About", "Home")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "Home")</li>
                    <li>@Html.ActionLink("NTDH: Khoa", "NTDHIndex", "NTDHKhoa")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - NGUYỄN THỊ DIỄM HƯƠNG</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>